language: scala
sudo: false
jdk:
  - openjdk8
script:
  - sbt ++${TRAVIS_SCALA_VERSION} test:compile checkScalariform
  - sbt ++${TRAVIS_SCALA_VERSION} test
matrix:
  include:
  - scala: 2.12.8
    jdk: openjdk11
  - os: windows
    language: bash
    env: JDK="adopt@1.8.212-04"
    before_script:
    - curl "https://raw.githubusercontent.com/DanySK/Gravis-CI/c8f400623d8f756ef7c/.install-jdk-travis.sh" --output .install-jdk-travis.sh
    - source .install-jdk-travis.sh
    - wget https://raw.githubusercontent.com/paulp/sbt-extras/0ee2dae2eba72efb4a464a5ad255e348696ecda7/sbt && chmod +x ./sbt
    script:
    - ./sbt "++ 2.12.8" test
