name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 3 * * 2'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - java: 8
            scala: 2
          - java: 8
            scala: 3
          - java: 11
            scala: 2
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - uses: coursier/cache-action@v6
    - run: |
        case ${{ matrix.scala }} in
          2)
            sbt -v "+ test:compile" checkScalariform "+ test"
            ;;
          3)
            sbt -v "++ 3.0.0-M3!" test
            ;;
          *)
            echo "unknown scala version"
            exit 1
        esac
