name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 3 * * 2'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - java: 8
          - java: 11
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - uses: coursier/cache-action@v6
    - run: sbt -v "+ Test/compile" checkScalariform "+ test"
